--- 
if: "github.actor == 'dependabot[bot]'"
jobs: 
  worker: 
    runs-on: ubuntu-latest
name: "Dependabot Automerge"
steps: 
  - 
    name: automerge
    uses: actions/github-script@0.2.0
    with: 
      github-token: "${{secrets.DEPENDABOT_TOKEN}}"
      script: |
          github.pullRequests.createReview({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number,
            event: 'APPROVE'
          })
          github.pullRequests.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number
          })
true: 
  pull_request: 
    schedule: 
      - 
        cron: "40 13 * * *"
